=== canonical/ubuntu-security-notices/schema/USN-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/canonical/ubuntu-security-notices/main/schema/USN-schema.json",
  "title": "Ubuntu Security Notice",
  "description": "A schema for describing a a security update in Ubuntu.",
  "type": "object",
  "properties": {
    "id": {
      "description": "The Security Notice id, e.g USN-0001-1",
      "type": "string"
    },
    "action": {
      "description": "Instructions on how to upgrade",
      "type": "string"
    },
    "cves": {
      "description": "A list of CVEs related to this Notice",
      "type": "array",
      "items": {
        "description": "CVE ID in the form of CVE-YYYY-NNNN",
        "type": "string"
      }
    },
    "description": {
      "description": "The description of the issue as written by the Security Team",
      "type": "string"
    },
    "is_hidden": {
      "description": "Temporary field used for testing purposes",
      "type": "string"
    },
    "isummary": {
      "description": "Short description of the vulnerability",
      "type": "string"
    },
    "releases": {
      "description": "An entry for each release name",
      "type": "object"
    },
    "summary": {
      "description": "Source package name and type of update, e.g. python-django vulnerability",
      "type": "string"
    },
    "timestamp": {
      "description": "Date in epoch format",
      "type": "number"
    },
    "title": {
      "description": "Similar to summary, but using the Official project name instead of source package name",
      "type": "string"
    }
  },
  "required": [
    "description",
    "id",
    "releases",
    "summary",
    "timestamp",
    "title"
  ],
  "additionalProperties": false
}

=== canonical/ubuntu-security-notices/usn/USN-5807-2.json
{
  "description": "USN-5807-1 fixed vulnerabilities in libXpm. This update provides the\ncorresponding updates for Ubuntu 16.04 ESM.\n\nOriginal advisory details:\n\n Martin Ettl discovered that libXpm incorrectly handled certain XPM files.\n If a user or automated system were tricked into opening a specially crafted\n XPM file, a remote attacker could possibly use this issue to cause libXpm\n to stop responding, resulting in a denial of service. (CVE-2022-44617)\n\n Marco Ivaldi discovered that libXpm incorrectly handled certain XPM files.\n If a user or automated system were tricked into opening a specially crafted\n XPM file, a remote attacker could possibly use this issue to cause libXpm\n to stop responding, resulting in a denial of service. (CVE-2022-46285)\n\n Alan Coopersmith discovered that libXpm incorrectly handled calling\n external helper binaries. If libXpm was being used by a setuid binary, a\n local attacker could possibly use this issue to escalate privileges.\n (CVE-2022-4883)\n",
  "releases": {
    "xenial": {
      "allbinaries": {
        "xpmutils": {
          "pocket": "esm-infra",
          "source": "libxpm",
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1"
        },
        "libxpm-dev": {
          "pocket": "esm-infra",
          "source": "libxpm",
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1"
        },
        "libxpm4": {
          "pocket": "esm-infra",
          "source": "libxpm",
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1"
        }
      },
      "binaries": {
        "xpmutils": {
          "pocket": "esm-infra",
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1"
        },
        "libxpm4": {
          "pocket": "esm-infra",
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1"
        }
      },
      "sources": {
        "libxpm": {
          "version": "1:3.5.11-1ubuntu0.16.04.1+esm1",
          "description": "X11 pixmap library"
        }
      }
    }
  },
  "title": "libXpm vulnerabilities",
  "timestamp": 1676972506.66655,
  "summary": "libxpm vulnerabilities",
  "action": "After a standard system update you need to restart your session to make all\nthe necessary changes.\n",
  "cves": [
    "CVE-2022-44617",
    "CVE-2022-46285",
    "CVE-2022-4883"
  ],
  "id": "USN-5807-2",
  "isummary": "Several security issues were fixed in libXpm.\n"
}

=== canonical/ubuntu-security-notices/usn/USN-7233-2.json
{
  "action": "After a standard system update you need to reboot your computer to make\nall the necessary changes.\n\nATTENTION: Due to an unavoidable ABI change the kernel updates have\nbeen given a new version number, which requires you to recompile and\nreinstall all third party kernel modules you might have installed.\nUnless you manually uninstalled the standard kernel metapackages\n(e.g. linux-generic, linux-generic-lts-RELEASE, linux-virtual,\nlinux-powerpc), a standard system upgrade will automatically perform\nthis as well.\n",
  "cves": [
    "CVE-2024-26595",
    "CVE-2024-26663",
    "CVE-2024-26929",
    "CVE-2024-38553",
    "CVE-2024-38597",
    "CVE-2024-38661",
    "CVE-2024-40982",
    "CVE-2024-41012",
    "CVE-2024-41020",
    "CVE-2024-41066",
    "CVE-2024-42252",
    "CVE-2024-42311",
    "CVE-2024-43914",
    "CVE-2024-53103",
    "CVE-2024-53141"
  ],
  "description": "Several security issues were discovered in the Linux kernel.\nAn attacker could possibly use these to compromise the system.\nThis update corrects flaws in the following subsystems:\n  - Multiple devices driver;\n  - Network drivers;\n  - Mellanox network drivers;\n  - S/390 drivers;\n  - SCSI subsystem;\n  - Sonic Silicon Backplane drivers;\n  - File systems infrastructure;\n  - Closures library;\n  - Netfilter;\n  - TIPC protocol;\n  - VMware vSockets driver;\n(CVE-2024-26929, CVE-2024-40982, CVE-2024-42311, CVE-2024-53141,\nCVE-2024-41066, CVE-2024-38661, CVE-2024-38553, CVE-2024-43914,\nCVE-2024-26663, CVE-2024-42252, CVE-2024-38597, CVE-2024-53103,\nCVE-2024-41020, CVE-2024-41012, CVE-2024-26595)\n",
  "id": "USN-7233-2",
  "isummary": "Several security issues were fixed in the Linux kernel.\n",
  "releases": {
    "bionic": {
      "allbinaries": {
        "linux-azure-4.15-cloud-tools-4.15.0-1185": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-azure-4.15-headers-4.15.0-1185": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-azure-4.15-tools-4.15.0-1185": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-buildinfo-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-cloud-tools-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-cloud-tools-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-headers-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-headers-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-image-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-signed-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-image-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-image-unsigned-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-modules-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-modules-extra-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-modules-extra-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-signed-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-signed-image-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        },
        "linux-tools-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "source": "linux-azure-4.15",
          "version": "4.15.0-1185.200"
        },
        "linux-tools-azure-lts-18.04": {
          "pocket": "esm-infra",
          "source": "linux-meta-azure-4.15",
          "version": "4.15.0.1185.153"
        }
      },
      "binaries": {
        "linux-image-4.15.0-1185-azure": {
          "pocket": "esm-infra",
          "version": "4.15.0-1185.200"
        },
        "linux-image-azure-lts-18.04": {
          "pocket": "esm-infra",
          "version": "4.15.0.1185.153"
        }
      },
      "sources": {
        "linux-azure-4.15": {
          "description": "Linux kernel for Microsoft Azure Cloud systems",
          "version": "4.15.0-1185.200"
        }
      }
    },
    "trusty": {
      "allbinaries": {
        "linux-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-azure-cloud-tools-4.15.0-1185": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-azure-headers-4.15.0-1185": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-azure-tools-4.15.0-1185": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-buildinfo-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-cloud-tools-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-cloud-tools-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-headers-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-headers-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-image-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-signed-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-image-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-image-unsigned-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-modules-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-modules-extra-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-modules-extra-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-signed-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-signed-image-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        },
        "linux-tools-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-azure",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-tools-azure": {
          "pocket": "esm-infra-legacy",
          "source": "linux-meta-azure",
          "version": "4.15.0.1185.200~14.04.1"
        }
      },
      "binaries": {
        "linux-image-4.15.0-1185-azure": {
          "pocket": "esm-infra-legacy",
          "version": "4.15.0-1185.200~14.04.1"
        },
        "linux-image-azure": {
          "pocket": "esm-infra-legacy",
          "version": "4.15.0.1185.200~14.04.1"
        }
      },
      "sources": {
        "linux-azure": {
          "description": "Linux kernel for Microsoft Azure Cloud systems",
          "version": "4.15.0-1185.200~14.04.1"
        }
      }
    }
  },
  "summary": "linux-azure, linux-azure-4.15 vulnerabilities",
  "timestamp": 1738263102.1910853,
  "title": "Linux kernel (Azure) vulnerabilities"
}

=== canonical/ubuntu-security-notices/usn/USN-3704-1.json
{
  "description": "It was discovered that devscripts incorrectly handled certain YAML files.\nAn attacker could possibly use this to execute arbitrary code.\n",
  "releases": {
    "bionic": {
      "allbinaries": {
        "devscripts": {
          "pocket": "security",
          "version": "2.17.12ubuntu1.1"
        }
      },
      "binaries": {
        "devscripts": {
          "pocket": "security",
          "version": "2.17.12ubuntu1.1"
        }
      },
      "archs": {
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_amd64.deb": {
              "size": 870376,
              "md5": "cbed8084d6224effb1d897b8559855dd"
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1.tar.xz": {
              "size": 712624,
              "md5": "686692ae8421726bb7e8ffdef060ab36"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1.dsc": {
              "size": 2713,
              "md5": "4fb0cbc35dc50a8f2fc63362f080af93"
            }
          }
        },
        "s390x": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_s390x.deb": {
              "size": 870364,
              "md5": "c066bbf69873b377f340557626a647d7"
            }
          }
        },
        "ppc64el": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_ppc64el.deb": {
              "size": 870732,
              "md5": "86a0f8586127ba14c3f1603bdff3fa88"
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_i386.deb": {
              "size": 870448,
              "md5": "b2fe263ce0d42c7312eecdf9c7addeaa"
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_armhf.deb": {
              "size": 870216,
              "md5": "2c7d021583194343a5b4872b8c7e13e1"
            }
          }
        },
        "arm64": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.12ubuntu1.1_arm64.deb": {
              "size": 870220,
              "md5": "95fc25b41f20ca1d869da366e4d7167a"
            }
          }
        }
      },
      "sources": {
        "devscripts": {
          "version": "2.17.12ubuntu1.1",
          "description": "scripts to make the life of a Debian Package maintainer easier"
        }
      }
    },
    "artful": {
      "sources": {
        "devscripts": {
          "version": "2.17.9ubuntu0.1",
          "description": "scripts to make the life of a Debian Package maintainer easier"
        }
      },
      "binaries": {
        "devscripts": {
          "version": "2.17.9ubuntu0.1"
        }
      },
      "archs": {
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_amd64.deb": {
              "size": 846708,
              "md5": "297802bf8ef12ba3623ea2a5c8da26fc"
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1.tar.xz": {
              "size": 696484,
              "md5": "37eb51f77216ef84a539b3ebcc4fcff6"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1.dsc": {
              "size": 2476,
              "md5": "c5161271df31194b784a1e16602ca4cc"
            }
          }
        },
        "s390x": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_s390x.deb": {
              "size": 846644,
              "md5": "275207781edac7038fa090f6539505d2"
            }
          }
        },
        "ppc64el": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_ppc64el.deb": {
              "size": 847074,
              "md5": "4854d6781718937a449b72a5c94b35fc"
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_i386.deb": {
              "size": 846772,
              "md5": "914d5a0bc5d95f94caa554e9fe1cc52c"
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_armhf.deb": {
              "size": 846612,
              "md5": "63a2378ad09930aa02e21fbcf88b6aa0"
            }
          }
        },
        "arm64": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/d/devscripts/devscripts_2.17.9ubuntu0.1_arm64.deb": {
              "size": 846556,
              "md5": "29e7a2d9f66efca7c21f33857c7aee87"
            }
          }
        }
      }
    }
  },
  "title": "devscripts vulnerability",
  "timestamp": 1530811565.798297,
  "summary": "devscripts vulnerability",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "cves": [
    "CVE-2018-13043"
  ],
  "id": "USN-3704-1",
  "isummary": "devscripts could be made to run arbitrary code if it received\na specially crafted YAML file.\n"
}
